### ISSUE TITLE
Tax revenue part of budgetary impact chart doesn't respect state

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-api#15]
At least that's my guess at what's happening here:

https://beta.policyengine.org/us/policy?reform=7&focus=policyOutput.netIncome&region=ny&timePeriod=2022&baseline=2

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/6076111/208523414-6c3efe3f-32fc-4ef5-8cff-9e5b7b84826c.png">

Though neither of the numbers matches the nationwide budgetary impact
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/6076111/208524069-907cf000-8ab0-4605-9372-a60869df3e51.png">

**Comment by MaxGhenis** [comment]
Actually maybe this reflects some broader issues with state filtering? e.g. it's not affecting poverty impacts.
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/6076111/208523781-1d7f4c93-18cd-4858-97a5-779c22f15449.png">
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/6076111/208523815-161ced00-2092-46c5-8a8a-60c3f6c8f8b0.png">

**Comment by nikhilwoodruff** [comment]
It's actually an issue with *State impacts affecting refundable credits*. Fixed in #21

**Comment by MaxGhenis** [comment]
This isn't fully fixed; e.g. the poverty impacts are identical between [national](https://beta.policyengine.org/us/policy?reform=7&focus=policyOutput.povertyImpact&timePeriod=2022&baseline=2&region=us) and [NY](https://beta.policyengine.org/us/policy?reform=7&focus=policyOutput.povertyImpact&region=ny&timePeriod=2022&baseline=2)

**Comment by MaxGhenis** [comment]
And now the [NY results aren't loading](https://beta.policyengine.org/us/policy?reform=7&focus=policyOutput.povertyImpact&region=ny&timePeriod=2022&baseline=2)

**Comment by MaxGhenis** [comment]
NY results now load, but they're again identical to national

**Comment by MaxGhenis** [comment]
[NY poverty impacts](https://beta.policyengine.org/us/policy?focus=policyOutput.povertyImpact&reform=14&region=ny&timePeriod=2022&baseline=2) now differ from [US poverty impacts](https://beta.policyengine.org/us/policy?focus=policyOutput.povertyImpact&reform=14&region=us&timePeriod=2022&baseline=2) for the refundable ctc reform
